FROM node:22-alpine

COPY package.json package-lock.json bun.lock jsconfig.json /app/
COPY src /app/
COPY .env /app/
COPY README.md .gitignore /app/


WORKDIR /app



RUN npm install

CMD ["npm","start"]




