const mongoose=require("mongoose")
const UserModel=mongoose.Schema({
    name:{
        type:String,
        required:true,
    },
    email:{
        type:String,
        required:true,
        unique:true
    },
    password:{
        type:String,
        required:true
    },
    phone:{
        type:String,
        required:true,
    },
    birthDay:{
        type:Date,
    },
    billing:{
        address:{
            type:String,
        },
        creditCardNumber:{
            type:String,
        },
        creditCardExpiry:{
            type:Date,
        },
        creditCardCVC:{
            type:String,
        },
        creditCardName:{
            type:String,
        }
    },
    wishlist:[{
        type:mongoose.Schema.Types.ObjectId,
        ref:"Product"
    }],
    cart:{
        type:mongoose.Schema.Types.ObjectId,
        ref:"Cart"
    },
    orders:[{
        type:mongoose.Schema.Types.ObjectId,
        ref:"Order"
    }],
    isAdmin:{
        type:Boolean,
        default:false
    },
    isSeller:{
        type:Boolean,
        default:false
    },
    isBlocked:{
        type:Boolean,
        default:false
    },
    isVerified:{
        type:Boolean,
        default:false
    },
    verificationToken:{
        type:String,
    },
    verificationTokenExpiry:{
        type:Date,
    },
    otpCode:{
        type:String,
    },
    profilePicture:{
        type:String,
    },
    createdAt:{
        type:Date,
        default:Date.now
    },
    updatedAt:{
        type:Date,
        default:Date.now
    }
})
module.exports=mongoose.model("User",UserModel)